server:
  port: 9099
  servlet:
    session:
      cookie:
        secure: false
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/island_editor?characterEncoding=UTF-8&useUnicode=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 123456
  mvc:
    hiddenmethod:
      filter:
        enabled: true
